name: Criacao de KT
description: Adicionar template para criar automaticamente um artigo de KT
title: "[KT]: "
labels: ["kt-video"]
body:
  - type: markdown
    attributes:
      value: |
        Kt maker

  - type: input
    id: link_video
    attributes:
      label: Link do Vídeo
      description: Forneça o link do vídeo relacionado ao artigo de KT
      placeholder: https://link_do_video.com

  - type: textarea
    id: bibliography
    attributes:
      label: Bibliografia
      description: Adicione a bibliografia ou referências para o artigo de KT
      placeholder: Adicione as referências aqui
