name: gera kt

on:
  issues:
    types: [labeled, completed]

jobs:
  create-page:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for 'kt-video' label
        id: check_label
        run: |
          issue_number=${{ github.event.issue.number }}
          repo_owner=${{ github.repository_owner }}
          repo_name=${{ github.event.repository.name }}
          labels=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${repo_owner}/${repo_name}/issues/${issue_number}/labels" | jq -r '.[].name')
          if [[ ! " ${labels[@]} " =~ " kt-video " ]]; then
            echo "Label 'kt-video' not found, exiting."
            exit 1
          fi

      - name: Create _posts directory
        run: mkdir -p _posts

      - name: Extract issue content
        id: extract_issue
        run: |
          date=$(date -u +"%Y-%m-%d")
          title="${{ github.event.issue.title }}"
          sanitized_title=$(echo "${title}" | tr -cd '[:alnum:]-' | tr ' ' '-')
          filename="_posts/${date}-${sanitized_title}.md"
          body="${{ github.event.issue.body }}"
          link_video=$(echo "$body" | grep -oP '(?<=https://www.youtube.com/watch\?v=|https://youtu.be/)[^ ]+')
          iframe="<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/${link_video}\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>"
          if [ -f "$filename" ]; then
            rm "$filename"
          fi
          {
            echo "---"
            echo "title: '${{ github.event.issue.title }}'"
            echo "date: ${date}"
            echo "permalink: /posts/${date:0:4}/${date:5:2}/${sanitized_title}/"
            echo "tags:"
            echo "  - gh-action"
            echo "  - kt-video"
            echo "---"
            echo ""
            echo "${iframe}"
            echo ""
            echo "${body}"
          } > "$filename"

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push
        run: |
          git add _posts/
          git commit -m "feat: post feito por action #${{ github.event.issue.number }} titulo ${{ github.event.issue.title }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.NEW_PAGE_TOKEN }}
